batch_size: 4
iters: 1000

train_dataset:
  type: RemoteSensing
  train_dataset_root: /media/sdd/ckli/my_try/seg-for-fun2/data/rs_data/train_data
  positive_train_dataset_list: class4_positive_train_aug.txt
  negetive_train_dataset_list: train_list_without4.txt
  negetive_ratio: 0.5
  transforms:
    - type: Resize
      target_size: [256, 256]
    - type: RandomHorizontalFlip
    - type: Normalize
    - type: MyRandomRotate90
  mode: train

val_dataset:
  type: RemoteSensing
  train_dataset_root: /media/sdd/ckli/my_try/seg-for-fun2/data/rs_data/train_data
  transforms:
    - type: Resize
      target_size: [256, 256]
    - type: Normalize
  mode: val

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

learning_rate:
  value: 0.01
  decay:
    type: poly
    power: 0.9
    end_lr: 0

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]

model:
  type: FCN
  backbone:
    type: HRNet_W18
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
    has_se: True
  pretrained: Null
  backbone_indices: [-1]
